// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismicT from "@prismicio/types";
import type * as prismic from "@prismicio/client";

type Simplify<T> = {
    [KeyType in keyof T]: T[KeyType];
};
/** Content for Homepage documents */
interface HomepageDocumentData {
    /**
     * Slice Zone field in *Homepage*
     *
     * - **Field Type**: Slice Zone
     * - **Placeholder**: *None*
     * - **API ID Path**: homepage.slices[]
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/slices
     *
     */
    slices: prismicT.SliceZone<HomepageDocumentDataSlicesSlice>;
}
/**
 * Slice for *Homepage → Slice Zone*
 *
 */
type HomepageDocumentDataSlicesSlice = BlogListsSlice | HeaderBackgroundImageSlice;
/**
 * Homepage document from Prismic
 *
 * - **API ID**: `homepage`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomepageDocument<Lang extends string = string> = prismicT.PrismicDocumentWithUID<Simplify<HomepageDocumentData>, "homepage", Lang>;
/** Content for page documents */
interface PageDocumentData {
    /**
     * Back icon field in *page*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: page.back_icon
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    back_icon: prismicT.ImageField<never>;
    /**
     * Slice Zone field in *page*
     *
     * - **Field Type**: Slice Zone
     * - **Placeholder**: *None*
     * - **API ID Path**: page.slices[]
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/slices
     *
     */
    slices: prismicT.SliceZone<PageDocumentDataSlicesSlice>;
}
/**
 * Slice for *page → Slice Zone*
 *
 */
type PageDocumentDataSlicesSlice = ParagraphSlice | BlogDetailWithPollSlice | FooterSlice;
/**
 * page document from Prismic
 *
 * - **API ID**: `page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PageDocument<Lang extends string = string> = prismicT.PrismicDocumentWithUID<Simplify<PageDocumentData>, "page", Lang>;
export type AllDocumentTypes = HomepageDocument | PageDocument;
/**
 * Primary content in BlogDetailWithPoll → Primary
 *
 */
interface BlogDetailWithPollSliceDefaultPrimary {
    /**
     * Title field in *BlogDetailWithPoll → Primary*
     *
     * - **Field Type**: Title
     * - **Placeholder**: This is where it all begins...
     * - **API ID Path**: blog_detail_with_poll.primary.title
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    title: prismicT.TitleField;
    /**
     * Description field in *BlogDetailWithPoll → Primary*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: A nice description of your feature
     * - **API ID Path**: blog_detail_with_poll.primary.description
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    description: prismicT.RichTextField;
    /**
     * Top Background Image field in *BlogDetailWithPoll → Primary*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: blog_detail_with_poll.primary.top_background_image
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    top_background_image: prismicT.ImageField<never>;
    /**
     * Clock icon field in *BlogDetailWithPoll → Primary*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: blog_detail_with_poll.primary.clock_icon
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    clock_icon: prismicT.ImageField<never>;
    /**
     * Short Icon field in *BlogDetailWithPoll → Primary*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: blog_detail_with_poll.primary.short_icon
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    short_icon: prismicT.ImageField<never>;
    /**
     * View Count Icon field in *BlogDetailWithPoll → Primary*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: blog_detail_with_poll.primary.view_count_icon
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    view_count_icon: prismicT.ImageField<never>;
    /**
     * Thumbnail Image field in *BlogDetailWithPoll → Primary*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: blog_detail_with_poll.primary.thumbnail_image
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    thumbnail_image: prismicT.ImageField<never>;
    /**
     * Back Button field in *BlogDetailWithPoll → Primary*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: blog_detail_with_poll.primary.back_button
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    back_button: prismicT.ImageField<never>;
}
/**
 * Item in BlogDetailWithPoll → Items
 *
 */
export interface BlogDetailWithPollSliceDefaultItem {
    /**
     * Slider Background field in *BlogDetailWithPoll → Items*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: blog_detail_with_poll.items[].slider_background
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    slider_background: prismicT.ImageField<never>;
    /**
     * Purple Background field in *BlogDetailWithPoll → Items*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: blog_detail_with_poll.items[].purple_background
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    purple_background: prismicT.ImageField<never>;
    /**
     * Clock Icon field in *BlogDetailWithPoll → Items*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: blog_detail_with_poll.items[].clock_icon
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    clock_icon: prismicT.ImageField<never>;
    /**
     * Short icon field in *BlogDetailWithPoll → Items*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: blog_detail_with_poll.items[].short_icon
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    short_icon: prismicT.ImageField<never>;
    /**
     * view icon field in *BlogDetailWithPoll → Items*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: blog_detail_with_poll.items[].view_icon
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    view_icon: prismicT.ImageField<never>;
    /**
     * Title field in *BlogDetailWithPoll → Items*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: blog_detail_with_poll.items[].title
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    title: prismicT.RichTextField;
    /**
     * Paragraph field in *BlogDetailWithPoll → Items*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: blog_detail_with_poll.items[].paragraph
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    paragraph: prismicT.RichTextField;
    /**
     * Question Label field in *BlogDetailWithPoll → Items*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: blog_detail_with_poll.items[].question_label
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    question_label: prismicT.RichTextField;
    /**
     * Question field in *BlogDetailWithPoll → Items*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: blog_detail_with_poll.items[].question
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    question: prismicT.RichTextField;
    /**
     * Poll Question field in *BlogDetailWithPoll → Items*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: blog_detail_with_poll.items[].poll_question
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    poll_question: prismicT.RichTextField;
    /**
     * Poll Question icon field in *BlogDetailWithPoll → Items*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: blog_detail_with_poll.items[].poll_question_icon
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    poll_question_icon: prismicT.ImageField<never>;
    /**
     * Poll Answer field in *BlogDetailWithPoll → Items*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: blog_detail_with_poll.items[].poll_answer
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    poll_answer: prismicT.RichTextField;
    /**
     * Poll Question 2 field in *BlogDetailWithPoll → Items*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: blog_detail_with_poll.items[].poll_question_2
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    poll_question_2: prismicT.RichTextField;
    /**
     * Poll Question 2 Icon field in *BlogDetailWithPoll → Items*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: blog_detail_with_poll.items[].poll_question_2_icon
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    poll_question_2_icon: prismicT.ImageField<never>;
    /**
     * Poll Answer 2 field in *BlogDetailWithPoll → Items*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: blog_detail_with_poll.items[].poll_answer_2
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    poll_answer_2: prismicT.RichTextField;
    /**
     * Poll Question 3 field in *BlogDetailWithPoll → Items*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: blog_detail_with_poll.items[].poll_question_3
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    poll_question_3: prismicT.RichTextField;
    /**
     * Poll Question 3 Icon field in *BlogDetailWithPoll → Items*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: blog_detail_with_poll.items[].poll_question_3_icon
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    poll_question_3_icon: prismicT.ImageField<never>;
    /**
     * Poll Answer 3 field in *BlogDetailWithPoll → Items*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: blog_detail_with_poll.items[].poll_answer_3
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    poll_answer_3: prismicT.RichTextField;
    /**
     * Content Link field in *BlogDetailWithPoll → Items*
     *
     * - **Field Type**: Content Relationship
     * - **Placeholder**: *None*
     * - **API ID Path**: blog_detail_with_poll.items[].content_link
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    content_link: prismicT.RelationField;
    /**
     * Paragraph 2 field in *BlogDetailWithPoll → Items*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: blog_detail_with_poll.items[].paragraph_2
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    paragraph_2: prismicT.RichTextField;
}
/**
 * Default variation for BlogDetailWithPoll Slice
 *
 * - **API ID**: `default`
 * - **Description**: `BlogDetailWithPoll`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type BlogDetailWithPollSliceDefault = prismicT.SharedSliceVariation<"default", Simplify<BlogDetailWithPollSliceDefaultPrimary>, Simplify<BlogDetailWithPollSliceDefaultItem>>;
/**
 * Slice variation for *BlogDetailWithPoll*
 *
 */
type BlogDetailWithPollSliceVariation = BlogDetailWithPollSliceDefault;
/**
 * BlogDetailWithPoll Shared Slice
 *
 * - **API ID**: `blog_detail_with_poll`
 * - **Description**: `BlogDetailWithPoll`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type BlogDetailWithPollSlice = prismicT.SharedSlice<"blog_detail_with_poll", BlogDetailWithPollSliceVariation>;
/**
 * Primary content in BlogLists → Primary
 *
 */
interface BlogListsSliceDefaultPrimary {
    /**
     * blog label field in *BlogLists → Primary*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: blog_lists.primary.blog_label
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    blog_label: prismicT.RichTextField;
}
/**
 * Item in BlogLists → Items
 *
 */
export interface BlogListsSliceDefaultItem {
    /**
     * BlogThumbnail field in *BlogLists → Items*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: blog_lists.items[].blogthumbnail
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    blogthumbnail: prismicT.ImageField<never>;
    /**
     * BlogTitle field in *BlogLists → Items*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: blog_lists.items[].blogtitle
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    blogtitle: prismicT.RichTextField;
    /**
     * BlogShortDescription field in *BlogLists → Items*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: blog_lists.items[].blogshortdescription
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    blogshortdescription: prismicT.KeyTextField;
    /**
     * ClockIcon field in *BlogLists → Items*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: blog_lists.items[].clockicon
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    clockicon: prismicT.ImageField<never>;
    /**
     * Time field in *BlogLists → Items*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: blog_lists.items[].time
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    time: prismicT.KeyTextField;
    /**
     * ShortsIcon field in *BlogLists → Items*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: blog_lists.items[].shortsicon
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    shortsicon: prismicT.ImageField<never>;
    /**
     * ShortsCount field in *BlogLists → Items*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: blog_lists.items[].shortscount
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    shortscount: prismicT.KeyTextField;
    /**
     * blog link field in *BlogLists → Items*
     *
     * - **Field Type**: Link
     * - **Placeholder**: *None*
     * - **API ID Path**: blog_lists.items[].blog_link
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    blog_link: prismicT.LinkField;
    /**
     * content link field in *BlogLists → Items*
     *
     * - **Field Type**: Content Relationship
     * - **Placeholder**: *None*
     * - **API ID Path**: blog_lists.items[].content_link
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    content_link: prismicT.RelationField;
    /**
     * blog link CTA field in *BlogLists → Items*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: blog_lists.items[].blog_link_cta
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    blog_link_cta: prismicT.KeyTextField;
}
/**
 * Default variation for BlogLists Slice
 *
 * - **API ID**: `default`
 * - **Description**: `BlogLists`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type BlogListsSliceDefault = prismicT.SharedSliceVariation<"default", Simplify<BlogListsSliceDefaultPrimary>, Simplify<BlogListsSliceDefaultItem>>;
/**
 * Slice variation for *BlogLists*
 *
 */
type BlogListsSliceVariation = BlogListsSliceDefault;
/**
 * BlogLists Shared Slice
 *
 * - **API ID**: `blog_lists`
 * - **Description**: `BlogLists`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type BlogListsSlice = prismicT.SharedSlice<"blog_lists", BlogListsSliceVariation>;
/**
 * Primary content in Footer → Primary
 *
 */
interface FooterSliceDefaultPrimary {
    /**
     * Like icon field in *Footer → Primary*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: footer.primary.like_icon
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    like_icon: prismicT.ImageField<never>;
    /**
     * Share icon field in *Footer → Primary*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: footer.primary.share_icon
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    share_icon: prismicT.ImageField<never>;
    /**
     * Comment Icon field in *Footer → Primary*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: footer.primary.comment_icon
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    comment_icon: prismicT.ImageField<never>;
    /**
     * Hearth Animation field in *Footer → Primary*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: footer.primary.hearth_animation
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    hearth_animation: prismicT.ImageField<never>;
    /**
     * title field in *Footer → Primary*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: footer.primary.title
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    title: prismicT.RichTextField;
    /**
     * description field in *Footer → Primary*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: footer.primary.description
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    description: prismicT.RichTextField;
    /**
     * Red Heart Icon  field in *Footer → Primary*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: footer.primary.red_heart_icon
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    red_heart_icon: prismicT.ImageField<never>;
    /**
     * Puzzle Image field in *Footer → Primary*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: footer.primary.puzzle_image
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    puzzle_image: prismicT.ImageField<never>;
}
/**
 * Default variation for Footer Slice
 *
 * - **API ID**: `default`
 * - **Description**: `Footer`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type FooterSliceDefault = prismicT.SharedSliceVariation<"default", Simplify<FooterSliceDefaultPrimary>, never>;
/**
 * Slice variation for *Footer*
 *
 */
type FooterSliceVariation = FooterSliceDefault;
/**
 * Footer Shared Slice
 *
 * - **API ID**: `footer`
 * - **Description**: `Footer`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type FooterSlice = prismicT.SharedSlice<"footer", FooterSliceVariation>;
/**
 * Primary content in HeaderBackgroundImage → Primary
 *
 */
interface HeaderBackgroundImageSliceDefaultPrimary {
    /**
     * Title field in *HeaderBackgroundImage → Primary*
     *
     * - **Field Type**: Title
     * - **Placeholder**: This is where it all begins...
     * - **API ID Path**: header_background_image.primary.title
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    title: prismicT.TitleField;
    /**
     * HeaderImage field in *HeaderBackgroundImage → Primary*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: header_background_image.primary.headerimage
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    headerimage: prismicT.ImageField<never>;
    /**
     * CancleIcon field in *HeaderBackgroundImage → Primary*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: header_background_image.primary.cancleicon
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    cancleicon: prismicT.ImageField<never>;
    /**
     * blog link field in *HeaderBackgroundImage → Primary*
     *
     * - **Field Type**: Content Relationship
     * - **Placeholder**: *None*
     * - **API ID Path**: header_background_image.primary.blog_link
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    blog_link: prismicT.RelationField;
    /**
     * nav link field in *HeaderBackgroundImage → Primary*
     *
     * - **Field Type**: Link
     * - **Placeholder**: *None*
     * - **API ID Path**: header_background_image.primary.nav_link
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    nav_link: prismicT.LinkField;
}
/**
 * Default variation for HeaderBackgroundImage Slice
 *
 * - **API ID**: `default`
 * - **Description**: `HeaderBackgroundImage`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type HeaderBackgroundImageSliceDefault = prismicT.SharedSliceVariation<"default", Simplify<HeaderBackgroundImageSliceDefaultPrimary>, never>;
/**
 * Slice variation for *HeaderBackgroundImage*
 *
 */
type HeaderBackgroundImageSliceVariation = HeaderBackgroundImageSliceDefault;
/**
 * HeaderBackgroundImage Shared Slice
 *
 * - **API ID**: `header_background_image`
 * - **Description**: `HeaderBackgroundImage`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type HeaderBackgroundImageSlice = prismicT.SharedSlice<"header_background_image", HeaderBackgroundImageSliceVariation>;
/**
 * Primary content in Paragraph → Primary
 *
 */
interface ParagraphSliceDefaultPrimary {
    /**
     * Title field in *Paragraph → Primary*
     *
     * - **Field Type**: Title
     * - **Placeholder**: This is where it all begins...
     * - **API ID Path**: paragraph.primary.title
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    title: prismicT.TitleField;
    /**
     * Description field in *Paragraph → Primary*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: A nice description of your feature
     * - **API ID Path**: paragraph.primary.description
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    description: prismicT.RichTextField;
}
/**
 * Item in Paragraph → Items
 *
 */
export interface ParagraphSliceDefaultItem {
    /**
     * Blog Detail Paragraph field in *Paragraph → Items*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: paragraph.items[].blog_detail_paragraph
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    blog_detail_paragraph: prismicT.RichTextField;
}
/**
 * Default variation for Paragraph Slice
 *
 * - **API ID**: `default`
 * - **Description**: `Paragraph`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type ParagraphSliceDefault = prismicT.SharedSliceVariation<"default", Simplify<ParagraphSliceDefaultPrimary>, Simplify<ParagraphSliceDefaultItem>>;
/**
 * Slice variation for *Paragraph*
 *
 */
type ParagraphSliceVariation = ParagraphSliceDefault;
/**
 * Paragraph Shared Slice
 *
 * - **API ID**: `paragraph`
 * - **Description**: `Paragraph`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type ParagraphSlice = prismicT.SharedSlice<"paragraph", ParagraphSliceVariation>;
declare module "@prismicio/client" {
    interface CreateClient {
        (repositoryNameOrEndpoint: string, options?: prismic.ClientConfig): prismic.Client<AllDocumentTypes>;
    }
    namespace Content {
        export type { HomepageDocumentData, HomepageDocumentDataSlicesSlice, HomepageDocument, PageDocumentData, PageDocumentDataSlicesSlice, PageDocument, AllDocumentTypes, BlogDetailWithPollSliceDefaultPrimary, BlogDetailWithPollSliceDefaultItem, BlogDetailWithPollSliceDefault, BlogDetailWithPollSliceVariation, BlogDetailWithPollSlice, BlogListsSliceDefaultPrimary, BlogListsSliceDefaultItem, BlogListsSliceDefault, BlogListsSliceVariation, BlogListsSlice, FooterSliceDefaultPrimary, FooterSliceDefault, FooterSliceVariation, FooterSlice, HeaderBackgroundImageSliceDefaultPrimary, HeaderBackgroundImageSliceDefault, HeaderBackgroundImageSliceVariation, HeaderBackgroundImageSlice, ParagraphSliceDefaultPrimary, ParagraphSliceDefaultItem, ParagraphSliceDefault, ParagraphSliceVariation, ParagraphSlice };
    }
}
