// Code generated by Slice Machine. DO NOT EDIT.

import BlogDetailWithPoll from './BlogDetailWithPoll';
import BlogDetails from './BlogDetails';
import BlogLists from './BlogLists';
import CommentModal from './CommentModal';
import FilterTags from './FilterTags';
import Footer from './Footer';
import HeaderBackgroundImage from './HeaderBackgroundImage';
import Paragraph from './Paragraph';
import Polling from './Polling';

export {
	BlogDetailWithPoll,
	BlogDetails,
	BlogLists,
	CommentModal,
	FilterTags,
	Footer,
	HeaderBackgroundImage,
	Paragraph,
	Polling,
};

export const components = {
	blog_detail_with_poll: BlogDetailWithPoll,
	blog_details: BlogDetails,
	blog_lists: BlogLists,
	comment_modal: CommentModal,
	filter_tags: FilterTags,
	footer: Footer,
	header_background_image: HeaderBackgroundImage,
	paragraph: Paragraph,
	polling: Polling,
};
