// Code generated by Slice Machine. DO NOT EDIT.

import BlogDetailWithPoll from './BlogDetailWithPoll';
import BlogLists from './BlogLists';
import Footer from './Footer';
import HeaderBackgroundImage from './HeaderBackgroundImage';
import Paragraph from './Paragraph';

export {
	BlogDetailWithPoll,
	BlogLists,
	Footer,
	HeaderBackgroundImage,
	Paragraph,
};

export const components = {
	blog_detail_with_poll: BlogDetailWithPoll,
	blog_lists: BlogLists,
	footer: Footer,
	header_background_image: HeaderBackgroundImage,
	paragraph: Paragraph,
};
